# Generated by Django 5.1.15 on 2026-08-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seguradora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnpj', models.CharField(help_text='Somente dígitos, sem máscara.', max_length=14, unique=True, verbose_name='CNPJ')),
                ('nome', models.CharField(max_length=255)),
                ('uf', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AM', 'AM'), ('AP', 'AP'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MS', 'MS'), ('MT', 'MT'), ('PA', 'PA'), ('PB', 'PB'), ('PE', 'PE'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RO', 'RO'), ('RR', 'RR'), ('RS', 'RS'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=2, verbose_name='UF')),
                ('nome_fantasia', models.CharField(blank=True, default='', max_length=255)),
                ('situacao_cadastral', models.CharField(blank=True, default='', max_length=100)),
                ('status_enriquecimento', models.CharField(choices=[('PENDENTE', 'Pendente'), ('CONCLUIDO', 'Concluído'), ('NAO_ENCONTRADO', 'Não encontrado'), ('ERRO', 'Erro')], default='PENDENTE', max_length=20)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'seguradora',
                'verbose_name_plural': 'seguradoras',
                'ordering': ('nome', 'id'),
                'indexes': [models.Index(fields=['uf'], name='seguradora_uf_idx'), models.Index(fields=['status_enriquecimento'], name='seguradora_status_idx')],
            },
        ),
    ]
